ruby new_task.rb 1 .
ruby new_task.rb 2 ..
ruby new_task.rb 3 ..
ruby new_task.rb 4 ..
ruby new_task.rb 5 ..
ruby new_task.rb 6 ..
ruby new_task.rb 7 ..
ruby new_task.rb 8 ..
ruby new_task.rb 9 ..
ruby new_task.rb 10 ..
ruby new_task.rb 11 ..
ruby new_task.rb 12 ..
ruby new_task.rb 13 ...
ruby new_task.rb 14 ..
ruby new_task.rb 15 ..
ruby new_task.rb 16 ..
